[package]
name = "webhooks"
version = "1.0.0"
authors = ["Micha Vie <micha@freeiam.com>"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "0.22.10"

[dev-dependencies.elrond-wasm-debug]
version = "0.22.10"
