[package]
name = "webhooks-meta"
version = "1.0.0"
edition = "2018"
publish = false

[dependencies.webhooks]
path = ".."

[dependencies.elrond-wasm]
version = "0.22.10"

[dependencies.elrond-wasm-debug]
version = "0.22.10"
